version: "3.9"

services:
  dragonfly:
    # the new redis
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ulimits:
      memlock: -1
    command:
      - "--save_schedule=*:*" # save for every 1 minute
      - "--dir=/data"
    expose:
      - 6379
    networks:
      - redis
    volumes:
      - "dragonfly_data:/data"
    restart: unless-stopped
  hykey:
    image: ghcr.io/leon-th/hykey
    restart: unless-stopped
    environment:
      - API_KEY=<KEY>
      - RUST_LOG=hykey=debug
      - REDIS_URL=redis://dragonfly:6379/
    networks:
      - redis
    ports:
      - '4000:4000'
networks:
  redis:
    driver: bridge
volumes:
  dragonfly_data:
